export type Locale = "en" | "es";

export const copy = {
  en: {
    practice: "Practice",
    voicePractice: "Voice practice",
    comingSoon: "Soon",
    yourSpace: "YOUR SPACE",
    newConversation: "New conversation",
    temporaryChat: "Temporary chat",
    chatNotSaved: "Your conversation is not saved.",
    workspace: "English practice",
    conversation: "Free conversation",
    language: "Interface language",
    english: "English",
    spanish: "Spanish",
    emptyTitle: "Let's talk in English.",
    emptyDescription: "Start with one of these ideas, or write about anything on your mind.",
    promptDay: "Talk about my day",
    promptFilm: "Recommend a film",
    promptCoffee: "Order a coffee",
    promptDayText: "I'd love to talk about my day.",
    promptFilmText: "Can you recommend a film and tell me why you like it?",
    promptCoffeeText: "Let's practice ordering a coffee at a café.",
    assistant: "Conversy",
    you: "You",
    composerLabel: "Your message in English",
    composerPlaceholder: "Write a message in English…",
    send: "Send message",
    keyboardHint: "Enter to send · Shift + Enter for a new line",
    thinking: "Thinking",
    replyErrorTitle: "Your message is still here, but the reply didn't come through.",
    retry: "Try again",
    tutor: "Tutor",
    tutorOpen: "Open English tutor",
    tutorUnread: "New tutor message",
    tutorNotificationTitle: "A note from your tutor",
    dismissTutorNotification: "Dismiss tutor notification",
    tutorCorrectionIntro: "A short example in English would be",
    tutorCorrectionPrefix: "Quick note: instead of",
    tutorCorrectionJoin: "you can use this example in English:",
    tutorTitle: "Your English tutor",
    tutorDescription: "A little guidance, right when you need it.",
    close: "Close tutor",
    recentFeedback: "Recent feedback",
    feedbackPending: "Your tutor is checking this message…",
    feedbackError: "Couldn't check this sentence.",
    feedbackErrorNetwork: "Couldn't reach the tutor service. Check that the backend is running.",
    feedbackErrorProvider: "The AI provider rejected the review. Check the model selected in llama.cpp.",
    feedbackErrorTimeout: "The model took too long to finish the review. Try again.",
    feedbackErrorIncomplete: "The model stopped before finishing the review. Try again.",
    feedbackErrorInvalid: "The model returned a review that couldn't be read. Try again.",
    feedbackErrorLanguage: "The tutor couldn't prepare the explanation in Spanish. Try again.",
    feedbackTitle: "A small note",
    correction: "A more natural way to say it",
    noCorrection: "This sounds good as it is.",
    askTutor: "Ask about a correction, grammar, or anything from your conversation.",
    tutorPlaceholder: "Ask your tutor…",
    sendQuestion: "Send question",
    tutorThinking: "Your tutor is thinking",
    tutorError: "Your question is still here, but the tutor couldn't reply.",
    tutorErrorNetwork: "Couldn't reach the tutor service. Check that NestJS and the model server are running.",
    tutorErrorProvider: "The AI provider rejected the request. Check the selected model and its settings.",
    tutorErrorTimeout: "The model took too long to reply. You can try again.",
    tutorErrorIncomplete: "The model stopped before finishing its reply. You can try again.",
    tutorErrorLanguage: "The tutor couldn't prepare a clear reply in Spanish. You can try again.",
    tutorErrorCode: "Error code",
    noFeedbackYet: "Feedback from your conversation will appear here.",
    newChatNotice: "A fresh temporary conversation is ready.",
    chatRegion: "English conversation",
    messagesRegion: "Conversation messages",
    tutorMessagesRegion: "Messages with your tutor",
    sidebarLabel: "Main navigation",
    selectedPractice: "English practice, selected",
    interfaceLanguage: "Interface language",
  },
  es: {
    practice: "Práctica",
    voicePractice: "Práctica por voz",
    comingSoon: "Pronto",
    yourSpace: "TU ESPACIO",
    newConversation: "Nueva conversación",
    temporaryChat: "Chat temporal",
    chatNotSaved: "Tu conversación no se guarda.",
    workspace: "Práctica de inglés",
    conversation: "Conversación libre",
    language: "Idioma de interfaz",
    english: "Inglés",
    spanish: "Español",
    emptyTitle: "Hablemos en inglés.",
    emptyDescription: "Elige una idea para empezar o escribe sobre lo que quieras.",
    promptDay: "Hablar de mi día",
    promptFilm: "Recomendar una película",
    promptCoffee: "Pedir un café",
    promptDayText: "I'd love to talk about my day.",
    promptFilmText: "Can you recommend a film and tell me why you like it?",
    promptCoffeeText: "Let's practice ordering a coffee at a café.",
    assistant: "Conversy",
    you: "Tú",
    composerLabel: "Tu mensaje en inglés",
    composerPlaceholder: "Escribe un mensaje en inglés…",
    send: "Enviar mensaje",
    keyboardHint: "Enter para enviar · Shift + Enter para saltar de línea",
    thinking: "Pensando",
    replyErrorTitle: "Tu mensaje sigue aquí, pero no llegó la respuesta.",
    retry: "Reintentar",
    tutor: "Tutor",
    tutorOpen: "Abrir tutor de inglés",
    tutorUnread: "Nuevo mensaje del tutor",
    tutorNotificationTitle: "Tu tutor te ha escrito",
    dismissTutorNotification: "Cerrar notificación del tutor",
    tutorCorrectionIntro: "Un ejemplo breve en inglés sería",
    tutorCorrectionPrefix: "¡Oye! En vez de",
    tutorCorrectionJoin: "puedes usar este ejemplo en inglés:",
    tutorTitle: "Tu tutor de inglés",
    tutorDescription: "Una pequeña orientación cuando la necesites.",
    close: "Cerrar tutor",
    recentFeedback: "Correcciones recientes",
    feedbackPending: "Tu tutor está revisando este mensaje…",
    feedbackError: "No se pudo revisar esta frase.",
    feedbackErrorNetwork: "No se pudo conectar con el tutor. Comprueba que NestJS esté activo.",
    feedbackErrorProvider: "El proveedor rechazó la revisión. Comprueba el modelo cargado en llama.cpp.",
    feedbackErrorTimeout: "El modelo tardó demasiado en revisar la frase. Inténtalo otra vez.",
    feedbackErrorIncomplete: "El modelo se quedó sin salida antes de terminar. Inténtalo otra vez.",
    feedbackErrorInvalid: "No se pudo interpretar la revisión del modelo. Inténtalo otra vez.",
    feedbackErrorLanguage: "El tutor no pudo preparar la explicación en español. Inténtalo otra vez.",
    feedbackTitle: "Un pequeño apunte",
    correction: "Una forma más natural de decirlo",
    noCorrection: "Tu frase suena bien así.",
    askTutor: "Pregunta sobre una corrección, gramática o cualquier parte de la conversación.",
    tutorPlaceholder: "Pregúntale a tu tutor…",
    sendQuestion: "Enviar pregunta",
    tutorThinking: "Tu tutor está pensando",
    tutorError: "Tu pregunta sigue aquí, pero el tutor no pudo responder.",
    tutorErrorNetwork: "No se pudo conectar con el tutor. Comprueba que NestJS y el servidor del modelo estén activos.",
    tutorErrorProvider: "El proveedor de IA rechazó la petición. Comprueba el modelo y su configuración.",
    tutorErrorTimeout: "El modelo tardó demasiado en responder. Puedes reintentarlo.",
    tutorErrorIncomplete: "El modelo se quedó sin salida antes de terminar. Puedes reintentarlo.",
    tutorErrorLanguage: "El tutor no pudo preparar una respuesta clara en español. Puedes reintentarlo.",
    tutorErrorCode: "Código de error",
    noFeedbackYet: "Las correcciones de la conversación aparecerán aquí.",
    newChatNotice: "Tu nueva conversación temporal está lista.",
    chatRegion: "Conversación en inglés",
    messagesRegion: "Mensajes de la conversación",
    tutorMessagesRegion: "Mensajes con tu tutor",
    sidebarLabel: "Navegación principal",
    selectedPractice: "Práctica de inglés, seleccionada",
    interfaceLanguage: "Idioma de interfaz",
  },
} satisfies Record<Locale, Record<string, string>>;
