export type Locale = "en" | "es";

export const copy = {
  en: {
    practice: "Practice",
    voicePractice: "Voice practice",
    comingSoon: "Soon",
    yourSpace: "YOUR SPACE",
    newConversation: "New conversation",
    temporaryChat: "Temporary chat",
    chatNotSaved: "Your conversation is not saved.",
    workspace: "English practice",
    conversation: "Free conversation",
    voiceConversation: "Voice conversation",
    language: "Interface language",
    english: "English",
    spanish: "Spanish",
    emptyTitle: "Let's talk in English.",
    emptyDescription: "Start with one of these ideas, or write about anything on your mind.",
    voiceEmptyTitle: "Let's speak in English.",
    voiceEmptyDescription: "Record a short voice message. Your transcript and tutor feedback will appear here.",
    voiceComposerHint: "Prepare the voice model, then record a message in English.",
    promptDay: "Talk about my day",
    promptFilm: "Recommend a film",
    promptCoffee: "Order a coffee",
    promptDayText: "I'd love to talk about my day.",
    promptFilmText: "Can you recommend a film and tell me why you like it?",
    promptCoffeeText: "Let's practice ordering a coffee at a café.",
    assistant: "Conversy",
    you: "You",
    composerLabel: "Your message in English",
    composerPlaceholder: "Write a message in English…",
    send: "Send message",
    keyboardHint: "Enter to send · Shift + Enter for a new line",
    recordAudio: "Record a voice message",
    stopRecording: "Stop recording",
    cancelRecording: "Discard recording",
    sendRecording: "Send voice message",
    recordingNow: "Recording",
    recordingPreview: "Voice message preview",
    recordingLimit: "Maximum recording length reached",
    microphoneDenied: "Microphone access was denied. Check your browser permissions.",
    recordingUnavailable: "Voice recording is not available in this browser.",
    recordingFailed: "The recording could not be created. Try again.",
    playAudio: "Play audio",
    stopAudio: "Stop audio",
    showTranscript: "Show text",
    hideTranscript: "Hide text",
    voiceReply: "Voice reply",
    generatingVoice: "Preparing audio…",
    retryVoice: "Retry audio",
    transcribing: "Transcribing voice message…",
    transcriptionFailed: "Couldn't transcribe this audio. You can retry or discard it.",
    retryTranscription: "Retry transcription",
    editTranscript: "Edit transcript",
    saveTranscript: "Save and retry",
    cancelTranscriptEdit: "Cancel",
    transcriptEdited: "Transcript corrected. Conversation and tutor are updating.",
    voiceNoCorrection: "No clear grammar error was detected. You can edit the transcript if a word was recognized incorrectly.",
    prepareWhisper: "Prepare voice model (~207 MB)",
    prepareLocalWhisper: "Load local voice model",
    preparingWhisper: "Preparing the voice model…",
    whisperReady: "Voice model ready on this device",
    whisperCached: "Voice model downloaded in this browser",
    loadCachedWhisper: "Load voice model from cache",
    whisperLoadFailed: "Couldn't load the local voice model",
    retryWhisper: "Retry model download",
    removeWhisper: "Remove downloaded model",
    prepareWhisperFirst: "Prepare the voice model before recording.",
    localVoiceUnavailable: "No local English voice is available in this browser.",
    audioUnavailable: "Audio is no longer available. The transcript is still here.",
    pronunciationUnavailable: "Pronunciation analysis is unavailable right now.",
    pronunciationLabel: "Pronunciation note",
    thinking: "Thinking",
    replyErrorTitle: "Your message is still here, but the reply didn't come through.",
    retry: "Try again",
    tutor: "Tutor",
    tutorOpen: "Open English tutor",
    tutorUnread: "New tutor message",
    tutorNotificationTitle: "A note from your tutor",
    dismissTutorNotification: "Dismiss tutor notification",
    tutorCorrectionIntro: "Quick correction:",
    tutorCorrectionPrefix: "Quick correction:",
    tutorCorrectionJoin: "write:",
    tutorTitle: "Your English tutor",
    tutorDescription: "A little guidance, right when you need it.",
    close: "Close tutor",
    recentFeedback: "Recent feedback",
    feedbackPending: "Your tutor is checking this message…",
    feedbackError: "Couldn't check this sentence.",
    feedbackErrorNetwork: "Couldn't reach the tutor service. Check that the backend is running.",
    feedbackErrorModel: "The tutor couldn't review this message because the model is unavailable. Try again when it's running.",
    feedbackErrorProvider: "The AI provider rejected the review. Check the model selected in llama.cpp.",
    feedbackErrorTimeout: "The model took too long to finish the review. Try again.",
    feedbackErrorIncomplete: "The model stopped before finishing the review. Try again.",
    feedbackErrorInvalid: "The model returned a review that couldn't be read. Try again.",
    feedbackErrorInconsistent: "The tutor couldn't verify its correction against your sentence. Try again.",
    feedbackErrorLanguage: "The tutor couldn't prepare the explanation in Spanish. Try again.",
    feedbackErrorInstructionLeak: "The tutor couldn't prepare a learner-facing explanation. Try again.",
    feedbackErrorTarget: "The tutor couldn't identify which message to review. Try again.",
    feedbackTitle: "A small note",
    correction: "A more natural way to say it",
    noCorrection: "This sounds good as it is.",
    askTutor: "Ask about a correction, grammar, or anything from your conversation.",
    tutorPlaceholder: "Ask your tutor…",
    sendQuestion: "Send question",
    tutorThinking: "Your tutor is thinking",
    tutorWaitingForConversation: "Waiting for Conversy to reply so your tutor has the latest message…",
    tutorError: "Your question is still here, but the tutor couldn't reply.",
    tutorErrorNetwork: "Couldn't reach the tutor service. Check that NestJS and the model server are running.",
    tutorErrorModel: "The tutor couldn't reply because the model is unavailable. Try again when it's running.",
    tutorErrorProvider: "The AI provider rejected the request. Check the selected model and its settings.",
    tutorErrorTimeout: "The model took too long to reply. You can try again.",
    tutorErrorIncomplete: "The model stopped before finishing its reply. You can try again.",
    tutorErrorLanguage: "The tutor couldn't prepare a clear reply in Spanish. You can try again.",
    tutorErrorInstructionLeak: "The tutor couldn't prepare a clear explanation. You can try again.",
    tutorErrorTarget: "The tutor couldn't identify which message you meant. Please clarify it and try again.",
    tutorErrorCode: "Error code",
    noFeedbackYet: "Feedback from your conversation will appear here.",
    newChatNotice: "A fresh temporary conversation is ready.",
    chatRegion: "English conversation",
    messagesRegion: "Conversation messages",
    tutorMessagesRegion: "Messages with your tutor",
    sidebarLabel: "Main navigation",
    openMobileMenu: "Open navigation menu",
    closeMobileMenu: "Close navigation menu",
    selectedPractice: "English practice, selected",
    selectedVoicePractice: "Voice practice, selected",
    interfaceLanguage: "Interface language",
  },
  es: {
    practice: "Práctica",
    voicePractice: "Práctica por voz",
    comingSoon: "Pronto",
    yourSpace: "TU ESPACIO",
    newConversation: "Nueva conversación",
    temporaryChat: "Chat temporal",
    chatNotSaved: "Tu conversación no se guarda.",
    workspace: "Práctica de inglés",
    conversation: "Conversación libre",
    voiceConversation: "Conversación por voz",
    language: "Idioma de interfaz",
    english: "Inglés",
    spanish: "Español",
    emptyTitle: "Hablemos en inglés.",
    emptyDescription: "Elige una idea para empezar o escribe sobre lo que quieras.",
    voiceEmptyTitle: "Hablemos en inglés.",
    voiceEmptyDescription: "Graba un mensaje corto. Aquí aparecerán la transcripción y las correcciones del tutor.",
    voiceComposerHint: "Prepara el modelo de voz y graba un mensaje en inglés.",
    promptDay: "Hablar de mi día",
    promptFilm: "Recomendar una película",
    promptCoffee: "Pedir un café",
    promptDayText: "I'd love to talk about my day.",
    promptFilmText: "Can you recommend a film and tell me why you like it?",
    promptCoffeeText: "Let's practice ordering a coffee at a café.",
    assistant: "Conversy",
    you: "Tú",
    composerLabel: "Tu mensaje en inglés",
    composerPlaceholder: "Escribe un mensaje en inglés…",
    send: "Enviar mensaje",
    keyboardHint: "Enter para enviar · Shift + Enter para saltar de línea",
    recordAudio: "Grabar un mensaje de voz",
    stopRecording: "Detener grabación",
    cancelRecording: "Descartar grabación",
    sendRecording: "Enviar mensaje de voz",
    recordingNow: "Grabando",
    recordingPreview: "Escuchar el mensaje antes de enviarlo",
    recordingLimit: "Se alcanzó la duración máxima de grabación",
    microphoneDenied: "No se concedió acceso al micrófono. Revisa los permisos del navegador.",
    recordingUnavailable: "Este navegador no permite grabar audio.",
    recordingFailed: "No se pudo crear la grabación. Inténtalo otra vez.",
    playAudio: "Reproducir audio",
    stopAudio: "Detener audio",
    showTranscript: "Mostrar texto",
    hideTranscript: "Ocultar texto",
    voiceReply: "Respuesta de voz",
    generatingVoice: "Preparando el audio…",
    retryVoice: "Reintentar audio",
    transcribing: "Transcribiendo el mensaje de voz…",
    transcriptionFailed: "No se pudo transcribir el audio. Puedes reintentarlo o descartarlo.",
    retryTranscription: "Reintentar transcripción",
    editTranscript: "Editar transcripción",
    saveTranscript: "Guardar y reprocesar",
    cancelTranscriptEdit: "Cancelar",
    transcriptEdited: "Transcripción corregida. Actualizando conversación y tutor.",
    voiceNoCorrection: "No detecté un error gramatical claro. Puedes editar la transcripción si alguna palabra se reconoció mal.",
    prepareWhisper: "Preparar modelo de voz (~207 MB)",
    prepareLocalWhisper: "Cargar modelo de voz local",
    preparingWhisper: "Preparando el modelo de voz…",
    whisperReady: "Modelo de voz listo en este dispositivo",
    whisperCached: "Modelo de voz descargado en este navegador",
    loadCachedWhisper: "Cargar el modelo desde la caché",
    whisperLoadFailed: "No se pudo cargar el modelo de voz local",
    retryWhisper: "Reintentar descarga del modelo",
    removeWhisper: "Eliminar modelo descargado",
    prepareWhisperFirst: "Prepara el modelo de voz antes de grabar.",
    localVoiceUnavailable: "Este navegador no tiene una voz local en inglés disponible.",
    audioUnavailable: "El audio ya no está disponible; la transcripción sigue aquí.",
    pronunciationUnavailable: "El análisis de pronunciación no está disponible ahora.",
    pronunciationLabel: "Apunte de pronunciación",
    thinking: "Pensando",
    replyErrorTitle: "Tu mensaje sigue aquí, pero no llegó la respuesta.",
    retry: "Reintentar",
    tutor: "Tutor",
    tutorOpen: "Abrir tutor de inglés",
    tutorUnread: "Nuevo mensaje del tutor",
    tutorNotificationTitle: "Tu tutor te ha escrito",
    dismissTutorNotification: "Cerrar notificación del tutor",
    tutorCorrectionIntro: "Apunte:",
    tutorCorrectionPrefix: "Apunte:",
    tutorCorrectionJoin: "escribe:",
    tutorTitle: "Tu tutor de inglés",
    tutorDescription: "Una pequeña orientación cuando la necesites.",
    close: "Cerrar tutor",
    recentFeedback: "Correcciones recientes",
    feedbackPending: "Tu tutor está revisando este mensaje…",
    feedbackError: "No se pudo revisar esta frase.",
    feedbackErrorNetwork: "No se pudo conectar con el tutor. Comprueba que NestJS esté activo.",
    feedbackErrorModel: "El tutor no pudo revisar el mensaje porque el modelo no está disponible. Inténtalo cuando vuelva a estar activo.",
    feedbackErrorProvider: "El proveedor rechazó la revisión. Comprueba el modelo cargado en llama.cpp.",
    feedbackErrorTimeout: "El modelo tardó demasiado en revisar la frase. Inténtalo otra vez.",
    feedbackErrorIncomplete: "El modelo se quedó sin salida antes de terminar. Inténtalo otra vez.",
    feedbackErrorInvalid: "No se pudo interpretar la revisión del modelo. Inténtalo otra vez.",
    feedbackErrorInconsistent: "El tutor no pudo comprobar que la corrección coincida con tu frase. Inténtalo otra vez.",
    feedbackErrorLanguage: "El tutor no pudo preparar la explicación en español. Inténtalo otra vez.",
    feedbackErrorInstructionLeak: "El tutor no pudo preparar una explicación clara para ti. Inténtalo otra vez.",
    feedbackErrorTarget: "El tutor no pudo identificar qué mensaje debía revisar. Inténtalo otra vez.",
    feedbackTitle: "Un pequeño apunte",
    correction: "Una forma más natural de decirlo",
    noCorrection: "Tu frase suena bien así.",
    askTutor: "Pregunta sobre una corrección, gramática o cualquier parte de la conversación.",
    tutorPlaceholder: "Pregúntale a tu tutor…",
    sendQuestion: "Enviar pregunta",
    tutorThinking: "Tu tutor está pensando",
    tutorWaitingForConversation: "Esperando la respuesta de Conversy para que el tutor tenga el último mensaje…",
    tutorError: "Tu pregunta sigue aquí, pero el tutor no pudo responder.",
    tutorErrorNetwork: "No se pudo conectar con el tutor. Comprueba que NestJS y el servidor del modelo estén activos.",
    tutorErrorModel: "El tutor no pudo responder porque el modelo no está disponible. Inténtalo cuando vuelva a estar activo.",
    tutorErrorProvider: "El proveedor de IA rechazó la petición. Comprueba el modelo y su configuración.",
    tutorErrorTimeout: "El modelo tardó demasiado en responder. Puedes reintentarlo.",
    tutorErrorIncomplete: "El modelo se quedó sin salida antes de terminar. Puedes reintentarlo.",
    tutorErrorLanguage: "El tutor no pudo preparar una respuesta clara en español. Puedes reintentarlo.",
    tutorErrorInstructionLeak: "El tutor no pudo preparar una explicación clara. Puedes reintentarlo.",
    tutorErrorTarget: "El tutor no pudo identificar a qué mensaje te referías. Acláralo y vuelve a intentarlo.",
    tutorErrorCode: "Código de error",
    noFeedbackYet: "Las correcciones de la conversación aparecerán aquí.",
    newChatNotice: "Tu nueva conversación temporal está lista.",
    chatRegion: "Conversación en inglés",
    messagesRegion: "Mensajes de la conversación",
    tutorMessagesRegion: "Mensajes con tu tutor",
    sidebarLabel: "Navegación principal",
    openMobileMenu: "Abrir menú de navegación",
    closeMobileMenu: "Cerrar menú de navegación",
    selectedPractice: "Práctica de inglés, seleccionada",
    selectedVoicePractice: "Práctica por voz, seleccionada",
    interfaceLanguage: "Idioma de interfaz",
  },
} satisfies Record<Locale, Record<string, string>>;
